[build]
  command = "npm run build:clean"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 